<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Prueba Tecnica Desarrollado En la mayor parte en PHP</title>

    <!-- Bootstrap -->
    <link href="assets/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <div class="row" style="padding-top: 40px">
            <div class="col-md-12">
                <form action="<?php echo HOST ?>/listar" method="POST" class="form-horizontal" style="">

                    <div class="form-inline col-md-3 col-md-offset-8" >
                        <label for="exampleInputEmail1">Email:</label>
                        <input type="text" class="form-control" name="email">
                    </div>

                    <div class="form-inline col-md-1">
                        <button class="btn btn-success" id="save-user"> Search</button>
                    </div>
                </form>

                </br>
                </br>
                </br>

                <!-- Tabla de listados -->
                <table id="example" class="table table-striped table-bordered dataTable no-footer">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Position</th>
                        <th>Salary</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($employees as $row): ?>
                    <tr>
                        <th><?php echo $row["name"] ?></th>
                        <th><?php echo $row["email"] ?></th>
                        <th><?php echo $row["position"] ?></th>
                        <th><?php echo $row["salary"] ?></th>
                        <th> <a href="<?php echo HOST ?>/detalles/<?php echo $row['id'] ?>"> Details</a> </th>
                    </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="assets/js/bootstrap.js"></script>
</body>
</html>

